# Generated by Django 4.2.2 on 2023-09-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_images_for_posts_posts_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='images',
        ),
    ]
